export const TEAMS: any =
  [
    {
      id: '1',
      name: 'Argentina',
      logo: 'assets/imgs/teams/argentina.png',
      group: 'D',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '2',
      name: 'Australia',
      logo: 'assets/imgs/teams/australia.png',
      group: 'C',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '3',
      name: 'Belgium',
      logo: 'assets/imgs/teams/belgium.png',
      group: 'G',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '4',
      name: 'Brazil',
      logo: 'assets/imgs/teams/brazil.png',
      group: 'E',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '5',
      name: 'Colombia',
      logo: 'assets/imgs/teams/colombia.png',
      group: 'H',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '6',
      name: 'Costa Rica',
      logo: 'assets/imgs/teams/costa-rica.png',
      group: 'E',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '7',
      name: 'Croatia',
      logo: 'assets/imgs/teams/croatia.png',
      group: 'D',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '8',
      name: 'Denmark',
      logo: 'assets/imgs/teams/denmark.png',
      group: 'C',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '9',
      name: 'Egypt',
      logo: 'assets/imgs/teams/egypt.png',
      group: 'A',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '10',
      name: 'England',
      logo: 'assets/imgs/teams/england.png',
      group: 'G',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '11',
      name: 'France',
      logo: 'assets/imgs/teams/france.png',
      group: 'C',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '12',
      name: 'Germany',
      logo: 'assets/imgs/teams/germany.png',
      group: 'F',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '13',
      name: 'Iceland',
      logo: 'assets/imgs/teams/iceland.png',
      group: 'D',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '14',
      name: 'Iran',
      logo: 'assets/imgs/teams/iran.png',
      group: 'B',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '15',
      name: 'Japan',
      logo: 'assets/imgs/teams/japan.png',
      group: 'H',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '16',
      name: 'Korea Republic',
      logo: 'assets/imgs/teams/south-korea.png',
      group: 'F',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '17',
      name: 'Mexico',
      logo: 'assets/imgs/teams/mexico.png',
      group: 'F',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '18',
      name: 'Morocco',
      logo: 'assets/imgs/teams/morocco.png',
      group: 'B',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '19',
      name: 'Nigeria',
      logo: 'assets/imgs/teams/nigeria.png',
      group: 'D',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '20',
      name: 'Panama',
      logo: 'assets/imgs/teams/panama.png',
      group: 'G',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '21',
      name: 'Portugal',
      logo: 'assets/imgs/teams/portugal.png',
      group: 'B',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '22',
      name: 'Peru',
      logo: 'assets/imgs/teams/peru.png',
      group: 'C',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '23',
      name: 'Poland',
      logo: 'assets/imgs/teams/poland.png',
      group: 'H',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '24',
      name: 'Russia',
      logo: 'assets/imgs/teams/russia.png',
      group: 'A',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '25',
      name: 'Saudi Arabia',
      logo: 'assets/imgs/teams/saudi-arabia.png',
      group: 'A',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '26',
      name: 'Senegal',
      logo: 'assets/imgs/teams/senegal.png',
      group: 'H',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '27',
      name: 'Serbia',
      logo: 'assets/imgs/teams/serbia.png',
      group: 'E',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '28',
      name: 'Spain',
      logo: 'assets/imgs/teams/spain.png',
      group: 'B',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '29',
      name: 'Sweden',
      logo: 'assets/imgs/teams/sweden.png',
      group: 'F',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '30',
      name: 'Switzerland',
      logo: 'assets/imgs/teams/switzerland.png',
      group: 'E',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '31',
      name: 'Tunisia',
      logo: 'assets/imgs/teams/tunisia.png',
      group: 'G',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    },
    {
      id: '32',
      name: 'Uruguay',
      logo: 'assets/imgs/teams/uruguay.png',
      group: 'A',
      players: [
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
        {name : 'Player Name yet to be announced'},
      ]
    }
  ];
