export const SCHEDULE : any =
  [{
    id : "0",
    name: "Match 1",
    group: "Group A",
    team1: 'Russia',
    team2 : 'Saudi Arabia',
    team1logo : 'assets/imgs/teams/russia.png',
    team2logo:'assets/imgs/teams/saudi-arabia.png',
    time : '18:00 Local Time',
    stadium: 'Luzhniki Stadium',
    city : 'Moscow',
    date :'Thursday 14 JUNE 2018',
    countDown : "June 14, 2018 18:00:00"
  },
    {
      id : "1",
      name: "Match 2",
      group: "Group A",
      team1: 'Egypt',
      team2 : 'Uruguay',
      team1logo : 'assets/imgs/teams/egypt.png',
      team2logo:'assets/imgs/teams/uruguay.png',
      time : '17:00 Local Time',
      stadium: 'Ekaterinburg Arena',
      city : 'Ekaterinburg',
      date :'Friday 15 JUNE 2018',
      countDown : "June 15, 2018 17:00:00"
    },
    {
      id : "2",
      name: "Match 3",
      group: "Group B",
      team1: 'Morocco',
      team2 : 'Iran',
      team1logo : 'assets/imgs/teams/morocco.png',
      team2logo:'assets/imgs/teams/iran.png',
      time : '18:00 Local Time',
      stadium: 'Saint Petersburg Stadium',
      city : 'Saint Petersburg',
      date :'Friday 15 JUNE 2018',
      countDown : "June 15, 2018 18:00:00"
    },
    {
      id : "3",
      name: "Match 4",
      group: "Group B",
      team1: 'Portugal',
      team2 : 'Spain',
      team1logo : 'assets/imgs/teams/portugal.png',
      team2logo:'assets/imgs/teams/spain.png',
      time : '21:00 Local Time',
      stadium: 'Fisht Stadium',
      city : 'Sochi',
      date :'Friday 15 JUNE 2018',
      countDown : "June 15, 2018 21:00:00"
    },
    {
      id : "4",
      name: "Match 5",
      group: "Group C",
      team1: 'France',
      team2 : 'Australia',
      team1logo : 'assets/imgs/teams/france.png',
      team2logo:'assets/imgs/teams/australia.png',
      time : '13:00 Local Time',
      stadium: 'Kazan Arena',
      city : 'Kazan',
      date :'Saturday 16 JUNE 2018',
      countDown : "June 16, 2018 13:00:00"
    },
    {
      id : "5",
      name: "Match 6",
      group: "Group D",
      team1: 'Argentina',
      team2 : 'Iceland',
      team1logo : 'assets/imgs/teams/argentina.png',
      team2logo:'assets/imgs/teams/iceland.png',
      time : '16:00 Local Time',
      stadium: 'Spartak Stadium',
      city : 'Moscow',
      date :'Saturday 16 JUNE 2018',
      countDown : "June 16, 2018 16:00:00"
    },
    {
      id : "6",
      name: "Match 7",
      group: "Group C",
      team1: 'Peru',
      team2 : 'Denmark',
      team1logo : 'assets/imgs/teams/peru.png',
      team2logo:'assets/imgs/teams/denmark.png',
      time : '19:00 Local Time',
      stadium: 'Mordovia Arena',
      city : 'Saransk',
      date :'Saturday 16 JUNE 2018',
      countDown : "June 16, 2018 19:00:00"
    },
    {
      id : "7",
      name: "Match 8",
      group: "Group D",
      team1: 'Croatia',
      team2 : 'Nigeria',
      team1logo : 'assets/imgs/teams/croatia.png',
      team2logo:'assets/imgs/teams/nigeria.png',
      time : '21:00 Local Time',
      stadium: 'Kaliningrad Stadium',
      city : 'Kaliningrad',
      date :'Saturday 16 JUNE 2018',
      countDown : "June 16, 2018 21:00:00"
    },
    {
      id : "8",
      name: "Match 9",
      group: "Group E",
      team1: 'Costa Rica',
      team2 : 'Serbia',
      team1logo : 'assets/imgs/teams/costa-rica.png',
      team2logo:'assets/imgs/teams/serbia.png',
      time : '16:00 Local Time',
      stadium: 'Samara Arena',
      city : 'Samara',
      date :'Sunday 17 JUNE 2018',
      countDown : "June 17, 2018 16:00:00"
    },
    {
      id : "9",
      name: "Match 10",
      group: "Group F",
      team1: 'Germany',
      team2 : 'Mexico',
      team1logo : 'assets/imgs/teams/germany.png',
      team2logo:'assets/imgs/teams/mexico.png',
      time : '18:00 Local Time',
      stadium: 'Luzhniki Stadium',
      city : 'Moscow',
      date :'Sunday 17 JUNE 2018',
      countDown : "June 17, 2018 18:00:00"
    },
    {
      id : "10",
      name: "Match 11",
      group: "Group E",
      team1: 'Brazil',
      team2 : 'Switzerland',
      team1logo : 'assets/imgs/teams/brazil.png',
      team2logo:'assets/imgs/teams/switzerland.png',
      time : '21:00 Local Time',
      stadium: 'Rostov Arena',
      city : 'Rostov-On-Don',
      date :'Sunday 17 JUNE 2018',
      countDown : "June 17, 2018 21:00:00"
    },
    {
      id : "11",
      name: "Match 12",
      group: "Group F",
      team1: 'Sweden',
      team2 : 'Korea Republic',
      team1logo : 'assets/imgs/teams/sweden.png',
      team2logo:'assets/imgs/teams/south-korea.png',
      time : '15:00 Local Time',
      stadium: 'Nizhny Novgorod Stadium',
      city : 'Nizhny Novgorod',
      date :'Monday 18 JUNE 2018',
      countDown : "June 18, 2018 15:00:00"
    },
    {
      id : "12",
      name: "Match 13",
      group: "Group G",
      team1: 'Belgium',
      team2 : 'Panama',
      team1logo : 'assets/imgs/teams/belgium.png',
      team2logo:'assets/imgs/teams/panama.png',
      time : '18:00 Local Time',
      stadium: 'Fisht Stadium',
      city : 'Sochi',
      date :'Monday 18 JUNE 2018',
      countDown : "June 18, 2018 18:00:00"
    },
    {
      id : "13",
      name: "Match 14",
      group: "Group G",
      team1: 'Tunisia',
      team2 : 'England',
      team1logo : 'assets/imgs/teams/tunisia.png',
      team2logo:'assets/imgs/teams/england.png',
      time : '21:00 Local Time',
      stadium: 'Volgograd Arena',
      city : 'Volgograd',
      date :'Monday 18 JUNE 2018',
      countDown : "June 18, 2018 21:00:00"
    },
    {
      id : "14",
      name: "Match 15",
      group: "Group H",
      team1: 'Colombia',
      team2 : 'Japan',
      team1logo : 'assets/imgs/teams/colombia.png',
      team2logo:'assets/imgs/teams/japan.png',
      time : '15:00 Local Time',
      stadium: 'Mordovia Arena',
      city : 'Saransk',
      date :'Tuesday 19 JUNE 2018',
      countDown : "June 19, 2018 15:00:00"
    },
    {
      id : "15",
      name: "Match 16",
      group: "Group H",
      team1: 'Poland',
      team2 : 'Senegal',
      team1logo : 'assets/imgs/teams/poland.png',
      team2logo:'assets/imgs/teams/senegal.png',
      time : '18:00 Local Time',
      stadium: 'Spartak Stadium',
      city : 'Moscow',
      date :'Tuesday 19 JUNE 2018',
      countDown : "June 19, 2018 18:00:00"
    },
    {
      id : "16",
      name: "Match 17",
      group: "Group A",
      team1: 'Russia',
      team2 : 'Egypt',
      team1logo : 'assets/imgs/teams/russia.png',
      team2logo:'assets/imgs/teams/egypt.png',
      time : '21:00 Local Time',
      stadium: 'Saint Petersburg Stadium',
      city : 'Saint Petersburg',
      date :'Tuesday 19 JUNE 2018',
      countDown : "June 19, 2018 21:00:00"
    },
    {
      id : "17",
      name: "Match 18",
      group: "Group B",
      team1: 'Portugal',
      team2 : 'Morocco',
      team1logo : 'assets/imgs/teams/portugal.png',
      team2logo:'assets/imgs/teams/morocco.png',
      time : '15:00 Local Time',
      stadium: 'Luzhniki Stadium',
      city : 'Moscow',
      date :'Wednesday 20 JUNE 2018',
      countDown : "June 20, 2018 15:00:00"
    },
    {
      id : "18",
      name: "Match 19",
      group: "Group A",
      team1: 'Uruguay',
      team2 : 'Saudi Arabia',
      team1logo : 'assets/imgs/teams/uruguay.png',
      team2logo:'assets/imgs/teams/saudi-arabia.png',
      time : '18:00 Local Time',
      stadium: 'Rostov Arena',
      city : 'Rostov-On-Don',
      date :'Wednesday 20 JUNE 2018',
      countDown : "June 20, 2018 18:00:00"
    },
    {
      id : "19",
      name: "Match 20",
      group: "Group B",
      team1: 'Iran',
      team2 : 'Spain',
      team1logo : 'assets/imgs/teams/iran.png',
      team2logo:'assets/imgs/teams/spain.png',
      time : '21:00 Local Time',
      stadium: 'Kazan Arena',
      city : 'Kazan',
      date :'Wednesday 20 JUNE 2018',
      countDown : "June 20, 2018 21:00:00"
    },
    {
      id : "20",
      name: "Match 21",
      group: "Group C",
      team1: 'Denmark',
      team2 : 'Australia',
      team1logo : 'assets/imgs/teams/denmark.png',
      team2logo:'assets/imgs/teams/australia.png',
      time : '16:00 Local Time',
      stadium: 'Samara Arena',
      city : 'Samara',
      date :'Thursday 21 JUNE 2018',
      countDown : "June 21, 2018 16:00:00"
    },
    {
      id : "21",
      name: "Match 22",
      group: "Group C",
      team1: 'France',
      team2 : 'Peru',
      team1logo : 'assets/imgs/teams/france.png',
      team2logo:'assets/imgs/teams/peru.png',
      time : '20:00 Local Time',
      stadium: 'Ekaterinburg Arena',
      city : 'Ekaterinburg',
      date :'Thursday 21 JUNE 2018',
      countDown : "June 21, 2018 20:00:00"
    },
    {
      id : "22",
      name: "Match 23",
      group: "Group D",
      team1: 'Argentina',
      team2 : 'Croatia',
      team1logo : 'assets/imgs/teams/argentina.png',
      team2logo:'assets/imgs/teams/croatia.png',
      time : '21:00 Local Time',
      stadium: 'Nizhny Novgorod Stadium',
      city : 'Nizhny Novgorod',
      date :'Thursday 21 JUNE 2018',
      countDown : "June 21, 2018 21:00:00"
    },
    {
      id : "23",
      name: "Match 24",
      group: "Group E",
      team1: 'Brazil',
      team2 : 'Costa Rica',
      team1logo : 'assets/imgs/teams/brazil.png',
      team2logo:'assets/imgs/teams/costa-rica.png',
      time : '15:00 Local Time',
      stadium: 'Saint Petersburg Stadium',
      city : 'Saint Petersburg',
      date :'Friday 22 JUNE 2018',
      countDown : "June 22, 2018 15:00:00"
    },
    {
      id : "24",
      name: "Match 25",
      group: "Group D",
      team1: 'Nigeria',
      team2 : 'Iceland',
      team1logo : 'assets/imgs/teams/nigeria.png',
      team2logo:'assets/imgs/teams/iceland.png',
      time : '18:00 Local Time',
      stadium: 'Volgograd Arena',
      city : 'Volgograd',
      date :'Friday 22 JUNE 2018',
      countDown : "June 22, 2018 18:00:00"
    },
    {
      id : "25",
      name: "Match 26",
      group: "Group E",
      team1: 'Serbia',
      team2 : 'Switzerland',
      team1logo : 'assets/imgs/teams/serbia.png',
      team2logo:'assets/imgs/teams/switzerland.png',
      time : '20:00 Local Time',
      stadium: 'Kaliningrad Stadium',
      city : 'Kaliningrad',
      date :'Friday 22 JUNE 2018',
      countDown : "June 22, 2018 20:00:00"
    },
    {
      id : "26",
      name: "Match 27",
      group: "Group G",
      team1: 'Belgium',
      team2 : 'Tunisia',
      team1logo : 'assets/imgs/teams/belgium.png',
      team2logo:'assets/imgs/teams/tunisia.png',
      time : '15:00 Local Time',
      stadium: 'Spartak Stadium',
      city : 'Moscow',
      date :'Saturday 23 JUNE 2018',
      countDown : "June 23, 2018 15:00:00"
    },
    {
      id : "27",
      name: "Match 28",
      group: "Group F",
      team1: 'Korea Republic',
      team2 : 'Mexico',
      team1logo : 'assets/imgs/teams/south-korea.png',
      team2logo:'assets/imgs/teams/mexico.png',
      time : '18:00 Local Time',
      stadium: 'Rostov Arena',
      city : 'Rostov-On-Don',
      date :'Saturday 23 JUNE 2018',
      countDown : "June 23, 2018 18:00:00"
    },
    {
      id : "28",
      name: "Match 29",
      group: "Group F",
      team1: 'Germany',
      team2 : 'Sweden',
      team1logo : 'assets/imgs/teams/germany.png',
      team2logo:'assets/imgs/teams/sweden.png',
      time : '21:00 Local Time',
      stadium: 'Fisht Stadium',
      city : 'Sochi',
      date :'Saturday 23 JUNE 2018',
      countDown : "June 23, 2018 21:00:00"
    },
    {
      id : "29",
      name: "Match 30",
      group: "Group G",
      team1: 'England',
      team2 : 'Panama',
      team1logo : 'assets/imgs/teams/england.png',
      team2logo:'assets/imgs/teams/panama.png',
      time : '15:00 Local Time',
      stadium: 'Nizhny Novgorod Stadium',
      city : 'Nizhny Novgorod',
      date :'Sunday 24 JUNE 2018',
      countDown : "June 24, 2018 15:00:00"
    },
    {
      id : "30",
      name: "Match 31",
      group: "Group H",
      team1: 'Japan',
      team2 : 'Senegal',
      team1logo : 'assets/imgs/teams/japan.png',
      team2logo:'assets/imgs/teams/senegal.png',
      time : '20:00 Local Time',
      stadium: 'Ekaterinburg Arena',
      city : 'Ekaterinburg',
      date :'Sunday 24 JUNE 2018',
      countDown : "June 24, 2018 20:00:00"
    },
    {
      id : "31",
      name: "Match 32",
      group: "Group H",
      team1: 'Poland',
      team2 : 'Colombia',
      team1logo : 'assets/imgs/teams/poland.png',
      team2logo:'assets/imgs/teams/colombia.png',
      time : '21:00 Local Time',
      stadium: 'Kazan Arena',
      city : 'Kazan',
      date :'Sunday 24 JUNE 2018',
      countDown : "June 24, 2018 21:00:00"
    },
    {
      id : "32",
      name: "Match 33",
      group: "Group A",
      team1: 'Uruguay',
      team2 : 'Russia',
      team1logo : 'assets/imgs/teams/uruguay.png',
      team2logo:'assets/imgs/teams/russia.png',
      time : '18:00 Local Time',
      stadium: 'Samara Arena',
      city : 'Samara',
      date :'Monday 25 JUNE 2018',
      countDown : "June 25, 2018 18:00:00"
    },
    {
      id : "33",
      name: "Match 34",
      group: "Group A",
      team1: 'Saudi Arabia',
      team2 : 'Egypt',
      team1logo : 'assets/imgs/teams/saudi-arabia.png',
      team2logo:'assets/imgs/teams/egypt.png',
      time : '17:00 Local Time',
      stadium: 'Volgograd Arena',
      city : 'Volgograd',
      date :'Monday 25 JUNE 2018',
      countDown : "June 25, 2018 17:00:00"
    },
    {
      id : "34",
      name: "Match 35",
      group: "Group B",
      team1: 'Iran',
      team2 : 'Portugal',
      team1logo : 'assets/imgs/teams/iran.png',
      team2logo:'assets/imgs/teams/portugal.png',
      time : '21:00 Local Time',
      stadium: 'Mordovia Arena',
      city : 'Saransk',
      date :'Monday 25 JUNE 2018',
      countDown : "June 25, 2018 21:00:00"
    },
    {
      id : "35",
      name: "Match 36",
      group: "Group B",
      team1: 'Spain',
      team2 : 'Morocco',
      team1logo : 'assets/imgs/teams/spain.png',
      team2logo:'assets/imgs/teams/morocco.png',
      time : '20:00 Local Time',
      stadium: 'Kaliningrad Stadium',
      city : 'Kaliningrad',
      date :'Monday 25 JUNE 2018',
      countDown : "June 25, 2018 20:00:00"
    },
    {
      id : "36",
      name: "Match 37",
      group: "Group C",
      team1: 'Denmark',
      team2 : 'France',
      team1logo : 'assets/imgs/teams/denmark.png',
      team2logo:'assets/imgs/teams/france.png',
      time : '17:00 Local Time',
      stadium: 'Luzhniki Stadium',
      city : 'Moscow',
      date :'Tuesday 26 JUNE 2018',
      countDown : "June 26, 2018 17:00:00"
    },
    {
      id : "37",
      name: "Match 38",
      group: "Group C",
      team1: 'Australia',
      team2 : 'Peru',
      team1logo : 'assets/imgs/teams/australia.png',
      team2logo:'assets/imgs/teams/peru.png',
      time : '17:00 Local Time',
      stadium: 'Fisht Stadium',
      city : 'Sochi',
      date :'Tuesday 26 JUNE 2018',
      countDown : "June 26, 2018 17:00:00"
    },
    {
      id : "38",
      name: "Match 39",
      group: "Group D",
      team1: 'Nigeria',
      team2 : 'Argentina',
      team1logo : 'assets/imgs/teams/nigeria.png',
      team2logo:'assets/imgs/teams/argentina.png',
      time : '21:00 Local Time',
      stadium: 'Saint Petersburg Stadium',
      city : 'St. Petersburg',
      date :'Tuesday 26 JUNE 2018',
      countDown : "June 26, 2018 21:00:00"
    },
    {
      id : "30",
      name: "Match 40",
      group: "Group D",
      team1: 'Iceland',
      team2 : 'Croatia',
      team1logo : 'assets/imgs/teams/iceland.png',
      team2logo:'assets/imgs/teams/croatia.png',
      time : '21:00 Local Time',
      stadium: 'Rostov Arena',
      city : 'Rostov-On-Don',
      date :'Tuesday 26 JUNE 2018',
      countDown : "June 26, 2018 21:00:00"
    },
    {
      id : "40",
      name: "Match 41",
      group: "Group F",
      team1: 'Mexico',
      team2 : 'Sweden',
      team1logo : 'assets/imgs/teams/mexico.png',
      team2logo:'assets/imgs/teams/sweden.png',
      time : '19:00 Local Time',
      stadium: 'Ekaterinburg Arena',
      city : 'Ekaterinburg',
      date :'Wednesday 27 JUNE 2018',
      countDown : "June 27, 2018 19:00:00"
    },
    {
      id : "41",
      name: "Match 42",
      group: "Group F",
      team1: 'Korea Republic',
      team2 : 'Germany',
      team1logo : 'assets/imgs/teams/south-korea.png',
      team2logo:'assets/imgs/teams/germany.png',
      time : '17:00 Local Time',
      stadium: 'Kazan Arena',
      city : 'Kazan',
      date :'Wednesday 27 JUNE 2018',
      countDown : "June 27, 2018 17:00:00"
    },
    {
      id : "42",
      name: "Match 43",
      group: "Group E",
      team1: 'Serbia',
      team2 : 'Brazil',
      team1logo : 'assets/imgs/teams/serbia.png',
      team2logo:'assets/imgs/teams/brazil.png',
      time : '21:00 Local Time',
      stadium: 'Spartak Stadium',
      city : 'Moscow',
      date :'Wednesday 27 JUNE 2018',
      countDown : "June 27, 2018 21:00:00"
    },
    {
      id : "43",
      name: "Match 44",
      group: "Group E",
      team1: 'Switzerland',
      team2 : 'Costa Rica',
      team1logo : 'assets/imgs/teams/switzerland.png',
      team2logo:'assets/imgs/teams/south-korea.png',
      time : '21:00 Local Time',
      stadium: 'Nizhny Novgorod Stadium',
      city : 'Nizhny Novgorod',
      date :'Wednesday 27 JUNE 2018',
      countDown : "June 27, 2018 21:00:00"
    },
    {
      id : "44",
      name: "Match 45",
      group: "Group H",
      team1: 'Japan',
      team2 : 'Poland',
      team1logo : 'assets/imgs/teams/japan.png',
      team2logo:'assets/imgs/teams/poland.png',
      time : '17:00 Local Time',
      stadium: 'Volgograd Arena',
      city : 'Volgograd',
      date :'Thursday 28 JUNE 2018',
      countDown : "June 28, 2018 17:00:00"
    },
    {
      id : "45",
      name: "Match 46",
      group: "Group H",
      team1: 'Senegal',
      team2 : 'Colombia',
      team1logo : 'assets/imgs/teams/senegal.png',
      team2logo:'assets/imgs/teams/colombia.png',
      time : '18:00 Local Time',
      stadium: 'Samara Arena',
      city : 'Samara',
      date :'Thursday 28 JUNE 2018',
      countDown : "June 28, 2018 18:00:00"
    },
    {
      id : "46",
      name: "Match 47",
      group: "Group G",
      team1: 'Panama',
      team2 : 'Tunisia',
      team1logo : 'assets/imgs/teams/panama.png',
      team2logo:'assets/imgs/teams/tunisia.png',
      time : '21:00 Local Time',
      stadium: 'Mordovia Arena',
      city : 'Saransk',
      date :'Thursday 28 JUNE 2018',
      countDown : "June 28, 2018 21:00:00"
    },
    {
      id : "47",
      name: "Match 48",
      group: "Group G",
      team1: 'England',
      team2 : 'Belgium',
      team1logo : 'assets/imgs/teams/england.png',
      team2logo:'assets/imgs/teams/belgium.png',
      time : '20:00 Local Time',
      stadium: 'Kaliningrad Stadium',
      city : 'Kaliningrad',
      date :'Thursday 28 JUNE 2018',
      countDown : "June 28, 2018 20:00:00"
    },
    {
      id : "48",
      name: "Match 49",
      group: "ROUND OF 16",
      team1: '1C',
      team2 : '2D',
      team1logo : 'assets/imgs/teams/tbc.png',
      team2logo:'assets/imgs/teams/tbc.png',
      time : '17:00 Local Time',
      stadium: 'Kazan Arena',
      city : 'Kazan',
      date :'Thursday 30 JUNE 2018',
      countDown : "June 30, 2018 17:00:00"
    },
    {
      id : "49",
      name: "Match 50",
      group: "ROUND OF 16",
      team1: '1A',
      team2 : '2B',
      team1logo : 'assets/imgs/teams/tbc.png',
      team2logo:'assets/imgs/teams/tbc.png',
      time : '21:00 Local Time',
      stadium: 'Fisht Stadium',
      city : 'Sochi',
      date :'Thursday 30 JUNE 2018',
      countDown : "June 30, 2018 21:00:00"
    },
    {
      id : "50",
      name: "Match 51",
      group: "ROUND OF 16",
      team1: '1B',
      team2 : '2A',
      team1logo : 'assets/imgs/teams/tbc.png',
      team2logo:'assets/imgs/teams/tbc.png',
      time : '17:00 Local Time',
      stadium: 'Luzhniki Stadium',
      city : 'Moscow',
      date :'Sunday 01 JULY 2018',
      countDown : "July 1, 2018 17:00:00"
    },
    {
      id : "51",
      name: "Match 52",
      group: "ROUND OF 16",
      team1: '1D',
      team2 : '2C',
      team1logo : 'assets/imgs/teams/tbc.png',
      team2logo:'assets/imgs/teams/tbc.png',
      time : '17:00 Local Time',
      stadium: 'Nizhny Novgorod Stadium',
      city : 'Nizhny Novgorod',
      date :'Sunday 01 JULY 2018',
      countDown : "July 1, 2018 17:00:00"
    },
    {
      id : "52",
      name: "Match 53",
      group: "ROUND OF 16",
      team1: '1E',
      team2 : '2F',
      team1logo : 'assets/imgs/teams/tbc.png',
      team2logo:'assets/imgs/teams/tbc.png',
      time : '18:00 Local Time',
      stadium: 'Samara Arena',
      city : 'Samara',
      date :'Monday 02 JULY 2018',
      countDown : "July 2, 2018 18:00:00"
    },
    {
      id : "53",
      name: "Match 54",
      group: "ROUND OF 16",
      team1: '1G',
      team2 : '2H',
      team1logo : 'assets/imgs/teams/tbc.png',
      team2logo:'assets/imgs/teams/tbc.png',
      time : '21:00 Local Time',
      stadium: 'Rostov Arena',
      city : 'Rostov-On-Don',
      date :'Monday 02 JULY 2018',
      countDown : "July 2, 2018 21:00:00"
    },
    {
      id : "54",
      name: "Match 55",
      group: "ROUND OF 16",
      team1: '1F',
      team2 : '2E',
      team1logo : 'assets/imgs/teams/tbc.png',
      team2logo:'assets/imgs/teams/tbc.png',
      time : '17:00 Local Time',
      stadium: 'Saint Petersburg Stadium',
      city : 'Saint Petersburg',
      date :'Tuesday 03 JULY 2018',
      countDown : "July 3, 2018 17:00:00"
    },
    {
      id : "55",
      name: "Match 56",
      group: "ROUND OF 16",
      team1: '1H',
      team2 : '2G',
      team1logo : 'assets/imgs/teams/tbc.png',
      team2logo:'assets/imgs/teams/tbc.png',
      time : '21:00 Local Time',
      stadium: 'Spartak Stadium',
      city : 'Moscow',
      date :'Tuesday 03 JULY 2018',
      countDown : "July 3, 2018 21:00:00"
    },
    {
      id : "56",
      name: "Match 57",
      group: "QUARTER-FINALS",
      team1: 'W49',
      team2 : 'W50',
      team1logo : 'assets/imgs/teams/tbc.png',
      team2logo:'assets/imgs/teams/tbc.png',
      time : '17:00 Local Time',
      stadium: 'Nizhny Novgorod Stadium',
      city : 'Nizhny Novgorod',
      date :'Friday 06 JULY 2018',
      countDown : "July 6, 2018 17:00:00"
    },
    {
      id : "57",
      name: "Match 58",
      group: "QUARTER-FINALS",
      team1: 'W53',
      team2 : 'W54',
      team1logo : 'assets/imgs/teams/tbc.png',
      team2logo:'assets/imgs/teams/tbc.png',
      time : '21:00 Local Time',
      stadium: 'Kazan Arena',
      city : 'Kazan',
      date :'Friday 06 JULY 2018',
      countDown : "July 6, 2018 21:00:00"
    },
    {
      id : "58",
      name: "Match 59",
      group: "QUARTER-FINALS",
      team1: 'W55',
      team2 : 'W56',
      team1logo : 'assets/imgs/teams/tbc.png',
      team2logo:'assets/imgs/teams/tbc.png',
      time : '18:00 Local Time',
      stadium: 'Samara Arena',
      city : 'Samara',
      date :'Saturday 07 JULY 2018',
      countDown : "July 7, 2018 18:00:00"
    },
    {
      id : "59",
      name: "Match 60",
      group: "QUARTER-FINALS",
      team1: 'W51',
      team2 : 'W52',
      team1logo : 'assets/imgs/teams/tbc.png',
      team2logo:'assets/imgs/teams/tbc.png',
      time : '21:00 Local Time',
      stadium: 'Fisht Stadium',
      city : 'Sochi',
      date :'Saturday 07 JULY 2018',
      countDown : "July 7, 2018 21:00:00"
    },
    {
      id : "60",
      name: "Match 61",
      group: "SEMI-FINALS",
      team1: 'W57',
      team2 : 'W58',
      team1logo : 'assets/imgs/teams/tbc.png',
      team2logo:'assets/imgs/teams/tbc.png',
      time : '21:00 Local Time',
      stadium: 'Saint Petersburg Stadium',
      city : 'Saint Petersburg',
      date :'Tuesday 10 JULY 2018',
      countDown : "July 10, 2018 21:00:00"
    },
    {
      id : "61",
      name: "Match 62",
      group: "SEMI-FINALS",
      team1: 'W59',
      team2 : 'W60',
      team1logo : 'assets/imgs/teams/tbc.png',
      team2logo:'assets/imgs/teams/tbc.png',
      time : '21:00 Local Time',
      stadium: 'Luzhniki Stadium',
      city : 'Moscow',
      date :'Wednesday 11 JULY 2018',
      countDown : "July 11, 2018 21:00:00"
    },
    {
      id : "62",
      name: "Match 63",
      group: "PLAY-OFF FOR THIRD PLACE",
      team1: 'L61',
      team2 : 'L62',
      team1logo : 'assets/imgs/teams/tbc.png',
      team2logo:'assets/imgs/teams/tbc.png',
      time : '17:00 Local Time',
      stadium: 'Saint Petersburg Stadium',
      city : 'Saint Petersburg',
      date :'Saturday 14 JULY 2018',
      countDown : "July 14, 2018 17:00:00"
    },
    {
      id : "63",
      name: "Match 64",
      group: "FINAL",
      team1: 'W61',
      team2 : 'W62',
      team1logo : 'assets/imgs/teams/tbc.png',
      team2logo:'assets/imgs/teams/tbc.png',
      time : '18:00 Local Time',
      stadium: 'Luzhniki Stadium',
      city : 'Moscow',
      date :'Sunday 15 JULY 2018',
      countDown : "July 15, 2018 18:00:00"
    }
  ];
